// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_headers`, `jwt_needs_refresh`, `persist_auth_response`, `try_refresh_blocking`

Future<void> login({required String username, required String password}) =>
    RustLib.instance.api
        .crateApiAuthLogin(username: username, password: password);

Future<void> register({required String username, required String password}) =>
    RustLib.instance.api
        .crateApiAuthRegister(username: username, password: password);

Future<void> serverLogout() => RustLib.instance.api.crateApiAuthServerLogout();
