// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/error.dart';
import '../types/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wallet_management_delete`, `wallet_management_get`, `wallet_management_headers`, `wallet_management_post_json`, `wallet_management_put_json`, `wallet_management_url`

Future<List<Wallet>> getWalletsApi() =>
    RustLib.instance.api.crateApiWalletsGetWalletsApi();

Future<Wallet> createWalletApi(
        {required String name, required String description}) =>
    RustLib.instance.api
        .crateApiWalletsCreateWalletApi(name: name, description: description);

Future<String> listWalletUsersApi({required String walletId}) =>
    RustLib.instance.api.crateApiWalletsListWalletUsersApi(walletId: walletId);

Future<String> searchWalletUsersApi(
        {required String walletId, required String query}) =>
    RustLib.instance.api
        .crateApiWalletsSearchWalletUsersApi(walletId: walletId, query: query);

Future<void> addUserToWalletApi(
        {required String walletId, required String username}) =>
    RustLib.instance.api.crateApiWalletsAddUserToWalletApi(
        walletId: walletId, username: username);

Future<void> updateWalletUserApi(
        {required String walletId,
        required String userId,
        required String role}) =>
    RustLib.instance.api.crateApiWalletsUpdateWalletUserApi(
        walletId: walletId, userId: userId, role: role);

Future<void> removeWalletUserApi(
        {required String walletId, required String userId}) =>
    RustLib.instance.api
        .crateApiWalletsRemoveWalletUserApi(walletId: walletId, userId: userId);

Future<String> createWalletInviteApi({required String walletId}) =>
    RustLib.instance.api
        .crateApiWalletsCreateWalletInviteApi(walletId: walletId);

Future<String> joinWalletByCodeApi({required String code}) =>
    RustLib.instance.api.crateApiWalletsJoinWalletByCodeApi(code: code);

Future<String> listUserGroupsApi({required String walletId}) =>
    RustLib.instance.api.crateApiWalletsListUserGroupsApi(walletId: walletId);

Future<String> createUserGroupApi(
        {required String walletId, required String name}) =>
    RustLib.instance.api
        .crateApiWalletsCreateUserGroupApi(walletId: walletId, name: name);

Future<void> updateUserGroupApi(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateApiWalletsUpdateUserGroupApi(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteUserGroupApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateApiWalletsDeleteUserGroupApi(
        walletId: walletId, groupId: groupId);

Future<String> listUserGroupMembersApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateApiWalletsListUserGroupMembersApi(
        walletId: walletId, groupId: groupId);

Future<void> addUserGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String username}) =>
    RustLib.instance.api.crateApiWalletsAddUserGroupMemberApi(
        walletId: walletId, groupId: groupId, username: username);

Future<void> removeUserGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String userId}) =>
    RustLib.instance.api.crateApiWalletsRemoveUserGroupMemberApi(
        walletId: walletId, groupId: groupId, userId: userId);

Future<String> listContactGroupsApi({required String walletId}) =>
    RustLib.instance.api
        .crateApiWalletsListContactGroupsApi(walletId: walletId);

Future<String> createContactGroupApi(
        {required String walletId, required String name}) =>
    RustLib.instance.api
        .crateApiWalletsCreateContactGroupApi(walletId: walletId, name: name);

Future<void> updateContactGroupApi(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateApiWalletsUpdateContactGroupApi(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteContactGroupApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateApiWalletsDeleteContactGroupApi(
        walletId: walletId, groupId: groupId);

Future<String> listContactGroupMembersApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateApiWalletsListContactGroupMembersApi(
        walletId: walletId, groupId: groupId);

Future<void> addContactGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateApiWalletsAddContactGroupMemberApi(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<void> removeContactGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateApiWalletsRemoveContactGroupMemberApi(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<String> listPermissionActionsApi({required String walletId}) =>
    RustLib.instance.api
        .crateApiWalletsListPermissionActionsApi(walletId: walletId);

Future<String> getMyPermissionsApi({required String walletId}) =>
    RustLib.instance.api.crateApiWalletsGetMyPermissionsApi(walletId: walletId);

Future<String> getPermissionMatrixApi({required String walletId}) =>
    RustLib.instance.api
        .crateApiWalletsGetPermissionMatrixApi(walletId: walletId);

Future<void> putPermissionMatrixApi(
        {required String walletId, required String entriesJson}) =>
    RustLib.instance.api.crateApiWalletsPutPermissionMatrixApi(
        walletId: walletId, entriesJson: entriesJson);

Future<String> getWalletPermissionsApi({required String walletId}) =>
    RustLib.instance.api
        .crateApiWalletsGetWalletPermissionsApi(walletId: walletId);

Future<void> setWalletPermissionsApi(
        {required String walletId, required String entriesJson}) =>
    RustLib.instance.api.crateApiWalletsSetWalletPermissionsApi(
        walletId: walletId, entriesJson: entriesJson);
