// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `add_contact_group_member`, `add_contact_to_groups`, `add_contact_to_system_group`, `add_user_group_member`, `add_user_to_system_group`, `contact_is_active`, `delete_contact_group`, `delete_user_group`, `remove_contact_group_member`, `remove_user_group_member`, `remove_wallet_user`, `rename_contact_group`, `rename_user_group`, `replace_contact_group_memberships`, `set_event_context`, `set_permission_matrix_entries`, `soft_delete_contact_row`, `soft_delete_transaction_row`, `soft_delete_transactions_for_contact`, `update_contact_row`, `update_transaction_row`, `update_wallet_user_role`, `upsert_contact_group`, `upsert_contact_row`, `upsert_transaction_row`, `upsert_user_group`, `upsert_wallet_user`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkProjection>>
abstract class SdkProjection implements RustOpaqueInterface {
  static Future<SdkProjection> default_() =>
      RustLib.instance.api.crateSdkProjectionSdkProjectionDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SdkProjection> newInstance() =>
      RustLib.instance.api.crateSdkProjectionSdkProjectionNew();
}
