// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `all_contact_ids_in_wallet`, `contact_group_ids_for_contact`, `contact_ids_in_group`, `is_wallet_owner`, `matrix_rows_for_user_groups`, `user_group_ids_for_user`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkPermissionStore>>
abstract class SdkPermissionStore implements RustOpaqueInterface {
  static Future<SdkPermissionStore> default_() =>
      RustLib.instance.api.crateSdkStoreSdkPermissionStoreDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SdkPermissionStore> newInstance() =>
      RustLib.instance.api.crateSdkStoreSdkPermissionStoreNew();
}
