[workspace]
resolver = "2"
members = [
    "crates/server",
    "crates/client",
    "crates/core/domain",
    "crates/core/applier",
    "crates/core/resolver",
    "crates/core/snapshots",
]

[profile.dev]
incremental = true
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
incremental = true
