// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_server_event_payload`, `event_data_discriminator`, `maybe_save_snapshot`, `parse_server_event_for_applier`, `rebuild_projection_tables`, `server_hash_key`

/// Push unsynced events to server, mark accepted as synced.
///
/// Wire contract (matches backend `DomainEvent` deserializer in
/// `backend/rust-api/src/domain/events.rs`):
/// - Client owns `id` (event_id, a UUID v4). Uniqueness is scoped per-wallet on the
///   server, so collisions are essentially impossible.
/// - Server echoes back `accepted: [<event_id>]` so we can mark local rows synced
///   (the client's local event id == the wire id == the server's event_id).
Future<void> pushUnsynced() =>
    RustLib.instance.api.crateServicesSyncPushUnsynced();

/// Pull server events for this wallet, merge into local.
///
/// Per-row chain-hash protocol (server migration 033):
///   - Client sends its `last_hash` (the `latest_hash` returned by the
///     previous pull). Server does `WHERE hash = ?` on
///     `user_readable_events`; found → returns events with greater id
///     (incremental). Not found / first sync → returns all events plus
///     `flush=true`.
///   - Client never validates the hash. The server is authoritative.
///   - If `flush` is set, client wipes local events for the wallet
///     before applying the returned batch.
Future<void> pullAndMerge() =>
    RustLib.instance.api.crateServicesSyncPullAndMerge();

/// Full sync: push, then pull. The pull handles visibility-change detection
/// itself via the hash comparison — no separate "check permissions" pass.
Future<void> fullSync() => RustLib.instance.api.crateServicesSyncFullSync();

/// Clear local wallet data and full pull so the client sees the server's permission-filtered view.
/// Use after permission matrix or group membership changes (hot update without logout).
Future<void> clearWalletAndResync({required String walletId}) =>
    RustLib.instance.api
        .crateServicesSyncClearWalletAndResync(walletId: walletId);

/// Invalidate permission cache, clear local data, and full resync. Use after contact group
/// membership or permission matrix changes so the client sees updated data without logout/login.
/// Only has effect when wallet_id is the current wallet.
Future<void> invalidatePermsCacheAndPull({required String walletId}) =>
    RustLib.instance.api
        .crateServicesSyncInvalidatePermsCacheAndPull(walletId: walletId);
