// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI wrapper: login with error conversion to String
Future<void> login({required String username, required String password}) =>
    RustLib.instance.api
        .crateHandlersAuthLogin(username: username, password: password);

/// FFI wrapper: register with error conversion to String
Future<void> register({required String username, required String password}) =>
    RustLib.instance.api
        .crateHandlersAuthRegister(username: username, password: password);
