// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Wallet>> getWalletsApi() =>
    RustLib.instance.api.crateHandlersWalletsGetWalletsApi();

Future<Wallet> createWalletApi(
        {required String name, required String description}) =>
    RustLib.instance.api.crateHandlersWalletsCreateWalletApi(
        name: name, description: description);

Future<String> listWalletUsersApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsListWalletUsersApi(walletId: walletId);

Future<String> searchWalletUsersApi(
        {required String walletId, required String query}) =>
    RustLib.instance.api.crateHandlersWalletsSearchWalletUsersApi(
        walletId: walletId, query: query);

Future<void> addUserToWalletApi(
        {required String walletId, required String username}) =>
    RustLib.instance.api.crateHandlersWalletsAddUserToWalletApi(
        walletId: walletId, username: username);

Future<void> updateWalletUserApi(
        {required String walletId,
        required String userId,
        required String role}) =>
    RustLib.instance.api.crateHandlersWalletsUpdateWalletUserApi(
        walletId: walletId, userId: userId, role: role);

Future<void> removeWalletUserApi(
        {required String walletId, required String userId}) =>
    RustLib.instance.api.crateHandlersWalletsRemoveWalletUserApi(
        walletId: walletId, userId: userId);

Future<String> createWalletInviteApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsCreateWalletInviteApi(walletId: walletId);

Future<String> joinWalletByCodeApi({required String code}) =>
    RustLib.instance.api.crateHandlersWalletsJoinWalletByCodeApi(code: code);

Future<String> listUserGroupsApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsListUserGroupsApi(walletId: walletId);

Future<String> createUserGroupApi(
        {required String walletId, required String name}) =>
    RustLib.instance.api
        .crateHandlersWalletsCreateUserGroupApi(walletId: walletId, name: name);

Future<void> updateUserGroupApi(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateHandlersWalletsUpdateUserGroupApi(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteUserGroupApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateHandlersWalletsDeleteUserGroupApi(
        walletId: walletId, groupId: groupId);

Future<String> listUserGroupMembersApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateHandlersWalletsListUserGroupMembersApi(
        walletId: walletId, groupId: groupId);

Future<void> addUserGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String username}) =>
    RustLib.instance.api.crateHandlersWalletsAddUserGroupMemberApi(
        walletId: walletId, groupId: groupId, username: username);

Future<void> removeUserGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String userId}) =>
    RustLib.instance.api.crateHandlersWalletsRemoveUserGroupMemberApi(
        walletId: walletId, groupId: groupId, userId: userId);

Future<String> listContactGroupsApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsListContactGroupsApi(walletId: walletId);

Future<String> createContactGroupApi(
        {required String walletId, required String name}) =>
    RustLib.instance.api.crateHandlersWalletsCreateContactGroupApi(
        walletId: walletId, name: name);

Future<void> updateContactGroupApi(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateHandlersWalletsUpdateContactGroupApi(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteContactGroupApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateHandlersWalletsDeleteContactGroupApi(
        walletId: walletId, groupId: groupId);

Future<String> listContactGroupMembersApi(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateHandlersWalletsListContactGroupMembersApi(
        walletId: walletId, groupId: groupId);

Future<void> addContactGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateHandlersWalletsAddContactGroupMemberApi(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<void> removeContactGroupMemberApi(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateHandlersWalletsRemoveContactGroupMemberApi(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<String> listPermissionActionsApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsListPermissionActionsApi(walletId: walletId);

Future<String> getMyPermissionsApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsGetMyPermissionsApi(walletId: walletId);

Future<String> getPermissionMatrixApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsGetPermissionMatrixApi(walletId: walletId);

Future<void> putPermissionMatrixApi(
        {required String walletId, required String entriesJson}) =>
    RustLib.instance.api.crateHandlersWalletsPutPermissionMatrixApi(
        walletId: walletId, entriesJson: entriesJson);

Future<String> getWalletPermissionsApi({required String walletId}) =>
    RustLib.instance.api
        .crateHandlersWalletsGetWalletPermissionsApi(walletId: walletId);

Future<void> setWalletPermissionsApi(
        {required String walletId, required String entriesJson}) =>
    RustLib.instance.api.crateHandlersWalletsSetWalletPermissionsApi(
        walletId: walletId, entriesJson: entriesJson);

Future<String> getContactGroupPermissionsApi(
        {required String walletId, required String contactGroupId}) =>
    RustLib.instance.api.crateHandlersWalletsGetContactGroupPermissionsApi(
        walletId: walletId, contactGroupId: contactGroupId);

Future<void> setContactGroupPermissionsApi(
        {required String walletId,
        required String contactGroupId,
        required String entriesJson}) =>
    RustLib.instance.api.crateHandlersWalletsSetContactGroupPermissionsApi(
        walletId: walletId,
        contactGroupId: contactGroupId,
        entriesJson: entriesJson);
