// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_headers`, `base_url`, `get_sync_events`, `get_sync_hash`, `post_sync_events`

/// POST /api/auth/login -> { token, user_id, username }
Future<void> login({required String username, required String password}) =>
    RustLib.instance.api.crateApiLogin(username: username, password: password);

/// GET /api/wallets
Future<List<Wallet>> getWalletsApi() =>
    RustLib.instance.api.crateApiGetWalletsApi();

/// POST /api/wallets - create wallet (server returns { id, name, message })
Future<Wallet> createWalletApi(
        {required String name, required String description}) =>
    RustLib.instance.api
        .crateApiCreateWalletApi(name: name, description: description);
