// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_backend_config`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BackendConfig`

/// Call once at startup with the app documents directory path (e.g. from path_provider).
/// Storage is process-wide; no need to call again from every thread.
Future<void> initStorage({required String storagePath}) =>
    RustLib.instance.api.crateConfigInitStorage(storagePath: storagePath);

Future<void> setBackendConfig(
        {required String baseUrl, required String wsUrl}) =>
    RustLib.instance.api
        .crateConfigSetBackendConfig(baseUrl: baseUrl, wsUrl: wsUrl);

Future<String> getBaseUrl() => RustLib.instance.api.crateConfigGetBaseUrl();

Future<String> getWsUrl() => RustLib.instance.api.crateConfigGetWsUrl();

/// Set whether the client is in "offline" mode. When true, all API requests return an error without hitting the network.
/// The app reconnects WS when going online; WS connection triggers sync (app logic, not here).
/// Thread-local (per test / per app when using multiple instances).
Future<void> setNetworkOffline({required bool offline}) =>
    RustLib.instance.api.crateConfigSetNetworkOffline(offline: offline);

/// True if the client is in offline mode (network requests will fail).
Future<bool> isNetworkOffline() =>
    RustLib.instance.api.crateConfigIsNetworkOffline();

/// Set or clear a per-thread log tag. When set, the multi-app log viewer can
/// distinguish which simulated app produced each log line. Stub today — the
/// log_bridge doesn't yet prepend it — but exposing the API unblocks the
/// integration test setup (`AppInstance::activate`) that calls it on every
/// app switch. If/when we want per-app prefixes, logging::push can read
/// LOG_CONTEXT and prepend it.
Future<void> setLogContext({required String ctx}) =>
    RustLib.instance.api.crateConfigSetLogContext(ctx: ctx);

/// Read the current per-thread log tag. Empty string if not set.
Future<String> logContext() => RustLib.instance.api.crateConfigLogContext();
