// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'crud.dart';
import 'dart:async';
import 'dart:convert';
import 'data_bus.dart';
import 'frb_generated.dart';
import 'ids.dart';
import 'lib.dart';
import 'log_bridge.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'sdk_projection.dart';
import 'sdk_snapshot_store.dart';
import 'sdk_store.dart';
import 'storage.dart';
import 'sync.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EventPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SdkPermissionStorePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SdkProjectionPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SdkSnapshotStorePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Event
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  SdkPermissionStore
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          dynamic raw);

  @protected
  SdkProjection
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          dynamic raw);

  @protected
  SdkSnapshotStore
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          dynamic raw);

  @protected
  Value
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  Event
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  Event
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  Event
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  SdkPermissionStore
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          dynamic raw);

  @protected
  SdkProjection
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          dynamic raw);

  @protected
  SdkSnapshotStore
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          dynamic raw);

  @protected
  Value
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  RustStreamSink<DataChangeEvent> dco_decode_StreamSink_data_change_event_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContactId dco_decode_box_autoadd_contact_id(dynamic raw);

  @protected
  Currency dco_decode_box_autoadd_currency(dynamic raw);

  @protected
  EventId dco_decode_box_autoadd_event_id(dynamic raw);

  @protected
  StoredEvent dco_decode_box_autoadd_stored_event(dynamic raw);

  @protected
  TransactionId dco_decode_box_autoadd_transaction_id(dynamic raw);

  @protected
  UserId dco_decode_box_autoadd_user_id(dynamic raw);

  @protected
  WalletId dco_decode_box_autoadd_wallet_id(dynamic raw);

  @protected
  Contact dco_decode_contact(dynamic raw);

  @protected
  ContactId dco_decode_contact_id(dynamic raw);

  @protected
  Currency dco_decode_currency(dynamic raw);

  @protected
  DataChangeEvent dco_decode_data_change_event(dynamic raw);

  @protected
  DataChangeKind dco_decode_data_change_kind(dynamic raw);

  @protected
  EventId dco_decode_event_id(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  JwtPayload dco_decode_jwt_payload(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StoredEvent> dco_decode_list_stored_event(dynamic raw);

  @protected
  List<Transaction> dco_decode_list_transaction(dynamic raw);

  @protected
  List<Wallet> dco_decode_list_wallet(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Currency? dco_decode_opt_box_autoadd_currency(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  StoredEvent dco_decode_stored_event(dynamic raw);

  @protected
  Transaction dco_decode_transaction(dynamic raw);

  @protected
  TransactionDirection dco_decode_transaction_direction(dynamic raw);

  @protected
  TransactionId dco_decode_transaction_id(dynamic raw);

  @protected
  TransactionType dco_decode_transaction_type(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserId dco_decode_user_id(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Wallet dco_decode_wallet(dynamic raw);

  @protected
  WalletId dco_decode_wallet_id(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Event
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  SdkPermissionStore
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          SseDeserializer deserializer);

  @protected
  SdkProjection
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          SseDeserializer deserializer);

  @protected
  SdkSnapshotStore
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  Event
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  Event
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  Event
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  SdkPermissionStore
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          SseDeserializer deserializer);

  @protected
  SdkProjection
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          SseDeserializer deserializer);

  @protected
  SdkSnapshotStore
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<DataChangeEvent> sse_decode_StreamSink_data_change_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContactId sse_decode_box_autoadd_contact_id(SseDeserializer deserializer);

  @protected
  Currency sse_decode_box_autoadd_currency(SseDeserializer deserializer);

  @protected
  EventId sse_decode_box_autoadd_event_id(SseDeserializer deserializer);

  @protected
  StoredEvent sse_decode_box_autoadd_stored_event(SseDeserializer deserializer);

  @protected
  TransactionId sse_decode_box_autoadd_transaction_id(
      SseDeserializer deserializer);

  @protected
  UserId sse_decode_box_autoadd_user_id(SseDeserializer deserializer);

  @protected
  WalletId sse_decode_box_autoadd_wallet_id(SseDeserializer deserializer);

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer);

  @protected
  ContactId sse_decode_contact_id(SseDeserializer deserializer);

  @protected
  Currency sse_decode_currency(SseDeserializer deserializer);

  @protected
  DataChangeEvent sse_decode_data_change_event(SseDeserializer deserializer);

  @protected
  DataChangeKind sse_decode_data_change_kind(SseDeserializer deserializer);

  @protected
  EventId sse_decode_event_id(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  JwtPayload sse_decode_jwt_payload(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StoredEvent> sse_decode_list_stored_event(SseDeserializer deserializer);

  @protected
  List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer);

  @protected
  List<Wallet> sse_decode_list_wallet(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Currency? sse_decode_opt_box_autoadd_currency(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  StoredEvent sse_decode_stored_event(SseDeserializer deserializer);

  @protected
  Transaction sse_decode_transaction(SseDeserializer deserializer);

  @protected
  TransactionDirection sse_decode_transaction_direction(
      SseDeserializer deserializer);

  @protected
  TransactionId sse_decode_transaction_id(SseDeserializer deserializer);

  @protected
  TransactionType sse_decode_transaction_type(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserId sse_decode_user_id(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Wallet sse_decode_wallet(SseDeserializer deserializer);

  @protected
  WalletId sse_decode_wallet_id(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          SdkPermissionStore self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          SdkProjection self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          SdkSnapshotStore self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          SdkPermissionStore self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          SdkProjection self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          SdkSnapshotStore self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_data_change_event_Sse(
      RustStreamSink<DataChangeEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_contact_id(
      ContactId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_currency(Currency self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event_id(EventId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stored_event(
      StoredEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transaction_id(
      TransactionId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_id(UserId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wallet_id(
      WalletId self, SseSerializer serializer);

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer);

  @protected
  void sse_encode_contact_id(ContactId self, SseSerializer serializer);

  @protected
  void sse_encode_currency(Currency self, SseSerializer serializer);

  @protected
  void sse_encode_data_change_event(
      DataChangeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_data_change_kind(
      DataChangeKind self, SseSerializer serializer);

  @protected
  void sse_encode_event_id(EventId self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_jwt_payload(JwtPayload self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_stored_event(
      List<StoredEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_transaction(
      List<Transaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wallet(List<Wallet> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_currency(
      Currency? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_stored_event(StoredEvent self, SseSerializer serializer);

  @protected
  void sse_encode_transaction(Transaction self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_direction(
      TransactionDirection self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_id(TransactionId self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_type(
      TransactionType self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_id(UserId self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet(Wallet self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_id(WalletId self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkPermissionStore(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkProjection(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkSnapshotStore(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr);
}
