// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_user_id_or_nil`, `current_user_id`, `jwt_payload`, `parse_resource`

Future<void> login({required String username, required String password}) =>
    RustLib.instance.api.crateLogin(username: username, password: password);

Future<void> register({required String username, required String password}) =>
    RustLib.instance.api.crateRegister(username: username, password: password);

Future<void> logout() => RustLib.instance.api.crateLogout();

Future<bool> isLoggedIn() => RustLib.instance.api.crateIsLoggedIn();

Future<String> getUserId() => RustLib.instance.api.crateGetUserId();

Future<String> getToken() => RustLib.instance.api.crateGetToken();

Future<void> setCurrentWalletId({required String walletId}) =>
    RustLib.instance.api.crateSetCurrentWalletId(walletId: walletId);

Future<String> getCurrentWalletId() =>
    RustLib.instance.api.crateGetCurrentWalletId();

Future<String> getWallets() => RustLib.instance.api.crateGetWallets();

Future<String> createWallet(
        {required String name, required String description}) =>
    RustLib.instance.api
        .crateCreateWallet(name: name, description: description);

Future<void> ensureCurrentWallet() =>
    RustLib.instance.api.crateEnsureCurrentWallet();

Future<String> getContacts() => RustLib.instance.api.crateGetContacts();

Future<String> getTransactions() => RustLib.instance.api.crateGetTransactions();

Future<String> getContact({required String id}) =>
    RustLib.instance.api.crateGetContact(id: id);

Future<String> createContact(
        {required String name,
        String? username,
        String? phone,
        String? email,
        String? notes,
        List<String>? groupIds}) =>
    RustLib.instance.api.crateCreateContact(
        name: name,
        username: username,
        phone: phone,
        email: email,
        notes: notes,
        groupIds: groupIds);

Future<String> createTransaction(
        {required String contactId,
        required String type,
        required String direction,
        required PlatformInt64 amount,
        required String currency,
        String? description,
        required String transactionDate,
        String? dueDate}) =>
    RustLib.instance.api.crateCreateTransaction(
        contactId: contactId,
        type: type,
        direction: direction,
        amount: amount,
        currency: currency,
        description: description,
        transactionDate: transactionDate,
        dueDate: dueDate);

Future<String> getTransaction({required String id}) =>
    RustLib.instance.api.crateGetTransaction(id: id);

Future<void> updateContact(
        {required String id,
        required String name,
        String? username,
        String? phone,
        String? email,
        String? notes,
        List<String>? groupIds}) =>
    RustLib.instance.api.crateUpdateContact(
        id: id,
        name: name,
        username: username,
        phone: phone,
        email: email,
        notes: notes,
        groupIds: groupIds);

Future<void> deleteContact({required String contactId}) =>
    RustLib.instance.api.crateDeleteContact(contactId: contactId);

Future<void> updateTransaction(
        {required String id,
        required String contactId,
        required String type,
        required String direction,
        required PlatformInt64 amount,
        required String currency,
        String? description,
        required String transactionDate,
        String? dueDate}) =>
    RustLib.instance.api.crateUpdateTransaction(
        id: id,
        contactId: contactId,
        type: type,
        direction: direction,
        amount: amount,
        currency: currency,
        description: description,
        transactionDate: transactionDate,
        dueDate: dueDate);

Future<void> deleteTransaction({required String transactionId}) =>
    RustLib.instance.api.crateDeleteTransaction(transactionId: transactionId);

Future<void> undoContactAction({required String contactId}) =>
    RustLib.instance.api.crateUndoContactAction(contactId: contactId);

Future<void> undoTransactionAction({required String transactionId}) =>
    RustLib.instance.api
        .crateUndoTransactionAction(transactionId: transactionId);

Future<void> bulkDeleteContacts({required List<String> contactIds}) =>
    RustLib.instance.api.crateBulkDeleteContacts(contactIds: contactIds);

Future<void> bulkDeleteTransactions({required List<String> transactionIds}) =>
    RustLib.instance.api
        .crateBulkDeleteTransactions(transactionIds: transactionIds);

Future<String> listWalletUsers({required String walletId}) =>
    RustLib.instance.api.crateListWalletUsers(walletId: walletId);

Future<String> searchWalletUsers(
        {required String walletId, required String query}) =>
    RustLib.instance.api
        .crateSearchWalletUsers(walletId: walletId, query: query);

Future<void> addUserToWallet(
        {required String walletId, required String username}) =>
    RustLib.instance.api
        .crateAddUserToWallet(walletId: walletId, username: username);

/// Create or replace 4-digit invite code for the wallet. Returns the code string.
Future<String> createWalletInviteCode({required String walletId}) =>
    RustLib.instance.api.crateCreateWalletInviteCode(walletId: walletId);

/// Join a wallet by invite code. Returns the wallet_id of the joined wallet.
Future<String> joinWalletByCode({required String code}) =>
    RustLib.instance.api.crateJoinWalletByCode(code: code);

Future<void> updateWalletUserRole(
        {required String walletId,
        required String userId,
        required String role}) =>
    RustLib.instance.api.crateUpdateWalletUserRole(
        walletId: walletId, userId: userId, role: role);

Future<void> removeWalletUser(
        {required String walletId, required String userId}) =>
    RustLib.instance.api
        .crateRemoveWalletUser(walletId: walletId, userId: userId);

Future<String> listWalletUserGroups({required String walletId}) =>
    RustLib.instance.api.crateListWalletUserGroups(walletId: walletId);

Future<String> createWalletUserGroup(
        {required String walletId, required String name}) =>
    RustLib.instance.api
        .crateCreateWalletUserGroup(walletId: walletId, name: name);

Future<void> updateWalletUserGroup(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateUpdateWalletUserGroup(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteWalletUserGroup(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api
        .crateDeleteWalletUserGroup(walletId: walletId, groupId: groupId);

Future<String> listWalletUserGroupMembers(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api
        .crateListWalletUserGroupMembers(walletId: walletId, groupId: groupId);

Future<void> addWalletUserGroupMember(
        {required String walletId,
        required String groupId,
        required String userId}) =>
    RustLib.instance.api.crateAddWalletUserGroupMember(
        walletId: walletId, groupId: groupId, userId: userId);

Future<void> removeWalletUserGroupMember(
        {required String walletId,
        required String groupId,
        required String userId}) =>
    RustLib.instance.api.crateRemoveWalletUserGroupMember(
        walletId: walletId, groupId: groupId, userId: userId);

Future<String> listWalletContactGroups({required String walletId}) =>
    RustLib.instance.api.crateListWalletContactGroups(walletId: walletId);

Future<String> createWalletContactGroup(
        {required String walletId, required String name}) =>
    RustLib.instance.api
        .crateCreateWalletContactGroup(walletId: walletId, name: name);

Future<void> updateWalletContactGroup(
        {required String walletId,
        required String groupId,
        required String name}) =>
    RustLib.instance.api.crateUpdateWalletContactGroup(
        walletId: walletId, groupId: groupId, name: name);

Future<void> deleteWalletContactGroup(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api
        .crateDeleteWalletContactGroup(walletId: walletId, groupId: groupId);

Future<String> listWalletContactGroupMembers(
        {required String walletId, required String groupId}) =>
    RustLib.instance.api.crateListWalletContactGroupMembers(
        walletId: walletId, groupId: groupId);

/// Returns JSON array of contact group ids that contain this contact. Used by edit-contact UI.
Future<String> getContactGroupIdsForContact(
        {required String walletId, required String contactId}) =>
    RustLib.instance.api.crateGetContactGroupIdsForContact(
        walletId: walletId, contactId: contactId);

Future<void> addWalletContactGroupMember(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateAddWalletContactGroupMember(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<void> removeWalletContactGroupMember(
        {required String walletId,
        required String groupId,
        required String contactId}) =>
    RustLib.instance.api.crateRemoveWalletContactGroupMember(
        walletId: walletId, groupId: groupId, contactId: contactId);

Future<String> listWalletPermissionActions({required String walletId}) =>
    RustLib.instance.api.crateListWalletPermissionActions(walletId: walletId);

Future<String> getMyPermissions({required String walletId}) =>
    RustLib.instance.api.crateGetMyPermissions(walletId: walletId);

Future<void> clearWalletData({required String walletId}) =>
    RustLib.instance.api.crateClearWalletData(walletId: walletId);

Future<String> getWalletPermissionMatrix({required String walletId}) =>
    RustLib.instance.api.crateGetWalletPermissionMatrix(walletId: walletId);

Future<void> putWalletPermissionMatrix(
        {required String walletId, required String entriesJson}) =>
    RustLib.instance.api.cratePutWalletPermissionMatrix(
        walletId: walletId, entriesJson: entriesJson);

Future<String> getEvents() => RustLib.instance.api.crateGetEvents();

/// Drain buffered Rust log lines so Dart can show them (e.g. via debugPrint).
Future<List<String>> drainRustLogs() =>
    RustLib.instance.api.crateDrainRustLogs();

Future<String> getPreference({required String key}) =>
    RustLib.instance.api.crateGetPreference(key: key);

Future<void> setPreference({required String key, required String value}) =>
    RustLib.instance.api.crateSetPreference(key: key, value: value);

Future<String> getUsername() => RustLib.instance.api.crateGetUsername();

/// True if JWT is expired or invalid. Used to avoid WebSocket 401 spam.
Future<bool> isTokenExpired() => RustLib.instance.api.crateIsTokenExpired();

/// Can the current user (taken from the stored JWT) perform `action_name`
/// (e.g. `"contact:create"`, `"transaction:read"`) on the resource named
/// by `(resource_type, resource_id)`?
///
/// `resource_type` is one of:
///   - `"contact"`, `"transaction"`, `"wallet"`,
///     `"contact_group"`, `"user_group"` — `resource_id` is the entity UUID.
///   - `"all_contacts"`, `"all_transactions"`, `"all_user_groups"` —
///     wildcard; `resource_id` is ignored.
///
/// Resolves entirely from the SDK's local SQLite permission tables —
/// no network call. The same rules the server enforces (3-state matrix,
/// deny wins, all_contacts wildcard) via the shared `resolver` crate.
/// Returns `Ok(false)` if no JWT / no current wallet (rather than an
/// error) so UI callers can use this from anywhere.
Future<bool> canPerform(
        {required String actionName,
        required String resourceType,
        String? resourceId}) =>
    RustLib.instance.api.crateCanPerform(
        actionName: actionName,
        resourceType: resourceType,
        resourceId: resourceId);

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateGreet(name: name);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Value>>
abstract class Value implements RustOpaqueInterface {}

class JwtPayload {
  final String? username;
  final bool expired;

  const JwtPayload({
    this.username,
    required this.expired,
  });

  static Future<JwtPayload> default_() =>
      RustLib.instance.api.crateJwtPayloadDefault();

  @override
  int get hashCode => username.hashCode ^ expired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JwtPayload &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          expired == other.expired;
}
