// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Push a log line (also prints to stderr). Called by rust_log! macro.
Future<void> push({required String s}) =>
    RustLib.instance.api.crateLogBridgePush(s: s);

/// Drain and clear buffered log lines. Dart calls this and debugPrint's each line.
Future<List<String>> drainRustLogs() =>
    RustLib.instance.api.crateLogBridgeDrainRustLogs();
