// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `count`, `delete_oldest_n`, `get_before_event_count`, `get_latest`, `next_snapshot_index`, `save`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkSnapshotStore>>
abstract class SdkSnapshotStore implements RustOpaqueInterface {
  static Future<SdkSnapshotStore> default_() =>
      RustLib.instance.api.crateSdkSnapshotStoreSdkSnapshotStoreDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SdkSnapshotStore> newInstance() =>
      RustLib.instance.api.crateSdkSnapshotStoreSdkSnapshotStoreNew();
}
