// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';

// These functions are ignored because they are not marked as `pub`: `apply_contact_event`, `apply_transaction_event`, `calculate_balances`, `parse_date`, `parse_ts`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BuildContact`, `BuildEvent`, `BuildTransaction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<(List<Contact>, List<Transaction>)> buildStateFromStored(
        {required List<StoredEvent> events}) =>
    RustLib.instance.api.crateStateBuilderBuildStateFromStored(events: events);
