// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_tables`, `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// True if init() has been called successfully (process-wide).
Future<bool> isReady() => RustLib.instance.api.crateStorageIsReady();

Future<void> init({required String path}) =>
    RustLib.instance.api.crateStorageInit(path: path);

Future<String?> configGet({required String key}) =>
    RustLib.instance.api.crateStorageConfigGet(key: key);

Future<void> configSet({required String key, required String value}) =>
    RustLib.instance.api.crateStorageConfigSet(key: key, value: value);

Future<void> configRemove({required String key}) =>
    RustLib.instance.api.crateStorageConfigRemove(key: key);

Future<void> clearAll() => RustLib.instance.api.crateStorageClearAll();

/// Drop everything wallet-scoped from local storage. Used when the
/// permission view diverges and the SDK needs a clean slate before
/// repulling, or when read access is revoked. All tables that hold
/// per-wallet projection state must be cleared together — leaving any
/// of them populated risks the SDK showing stale data the user has
/// lost access to.
Future<void> clearWallet({required String walletId}) =>
    RustLib.instance.api.crateStorageClearWallet(walletId: walletId);

Future<void> eventsInsert({required StoredEvent e}) =>
    RustLib.instance.api.crateStorageEventsInsert(e: e);

/// Update event_data JSON for an event (e.g. to add total_debt after rebuild).
Future<void> eventsUpdateEventData(
        {required String eventId, required String eventDataJson}) =>
    RustLib.instance.api.crateStorageEventsUpdateEventData(
        eventId: eventId, eventDataJson: eventDataJson);

Future<List<StoredEvent>> eventsGetAll({required String walletId}) =>
    RustLib.instance.api.crateStorageEventsGetAll(walletId: walletId);

Future<List<StoredEvent>> eventsGetUnsynced({required String walletId}) =>
    RustLib.instance.api.crateStorageEventsGetUnsynced(walletId: walletId);

Future<void> eventsMarkSynced({required List<String> ids}) =>
    RustLib.instance.api.crateStorageEventsMarkSynced(ids: ids);

/// Delete all unsynced (pending) events for a wallet.
Future<BigInt> eventsDeleteUnsynced({required String walletId}) =>
    RustLib.instance.api.crateStorageEventsDeleteUnsynced(walletId: walletId);

/// Delete all events for a wallet. Used on full pull so local state is replaced by server response (permission-filtered).
/// Drop only the events + their derived projection tables for a wallet.
/// Used by the hash-divergence path in pull_and_merge before refetching
/// from the server. Same wipe scope as `clear_wallet` minus the
/// last_sync_timestamp config row (which the caller manages).
Future<void> eventsDeleteAllForWallet({required String walletId}) =>
    RustLib.instance.api
        .crateStorageEventsDeleteAllForWallet(walletId: walletId);

Future<PlatformInt64> eventsCount({required String walletId}) =>
    RustLib.instance.api.crateStorageEventsCount(walletId: walletId);

/// Get all events for an aggregate, sorted by timestamp ascending (oldest first).
Future<List<StoredEvent>> eventsGetForAggregate(
        {required String walletId,
        required String aggregateType,
        required String aggregateId}) =>
    RustLib.instance.api.crateStorageEventsGetForAggregate(
        walletId: walletId,
        aggregateType: aggregateType,
        aggregateId: aggregateId);

/// Load contacts for a wallet straight from the projection table. The
/// computed `balance` field per contact is SUM of that contact's
/// transaction amounts, computed in SQL.
Future<List<Contact>> loadContactsFromTables({required String walletId}) =>
    RustLib.instance.api.crateStorageLoadContactsFromTables(walletId: walletId);

Future<List<Transaction>> loadTransactionsFromTables(
        {required String walletId}) =>
    RustLib.instance.api
        .crateStorageLoadTransactionsFromTables(walletId: walletId);

class StoredEvent {
  final String id;
  final String walletId;
  final String aggregateType;
  final String aggregateId;
  final String eventType;
  final String eventData;
  final String timestamp;
  final int version;
  final bool synced;

  const StoredEvent({
    required this.id,
    required this.walletId,
    required this.aggregateType,
    required this.aggregateId,
    required this.eventType,
    required this.eventData,
    required this.timestamp,
    required this.version,
    required this.synced,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      walletId.hashCode ^
      aggregateType.hashCode ^
      aggregateId.hashCode ^
      eventType.hashCode ^
      eventData.hashCode ^
      timestamp.hashCode ^
      version.hashCode ^
      synced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          walletId == other.walletId &&
          aggregateType == other.aggregateType &&
          aggregateId == other.aggregateId &&
          eventType == other.eventType &&
          eventData == other.eventData &&
          timestamp == other.timestamp &&
          version == other.version &&
          synced == other.synced;
}
