// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `last_sync_key`

/// Push unsynced events to server, mark accepted as synced.
Future<void> pushUnsynced() => RustLib.instance.api.crateSyncPushUnsynced();

/// Pull server events (since last sync for this wallet), merge into local, rebuild state.
/// When we have zero local events for this wallet, do a full pull (no since) so server data loads.
Future<void> pullAndMerge() => RustLib.instance.api.crateSyncPullAndMerge();

/// Full sync: push then pull.
Future<void> fullSync() => RustLib.instance.api.crateSyncFullSync();
