// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit`, `kind_from_aggregate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `hash`

/// Subscribe to data-change events. Dart calls this once at startup
/// and listens to the returned Stream for the app's lifetime. If
/// called more than once the previous sink is replaced — old
/// subscribers stop receiving events.
Stream<DataChangeEvent> dataChangeStream() =>
    RustLib.instance.api.crateIntegrationDataBusDataChangeStream();

/// One data-change notification.
class DataChangeEvent {
  /// Wallet the change applies to. `None` for cross-wallet changes
  /// like wallet creation/deletion.
  final String? walletId;
  final DataChangeKind kind;

  const DataChangeEvent({
    this.walletId,
    required this.kind,
  });

  @override
  int get hashCode => walletId.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataChangeEvent &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          kind == other.kind;
}

/// Categories of data that providers can listen for. New variants are
/// safe to add — Dart providers ignore kinds they don't care about.
enum DataChangeKind {
  /// Contacts changed in the given wallet.
  contacts,

  /// Transactions changed in the given wallet.
  transactions,

  /// Permission matrix / groups / wallet ownership changed.
  permissions,

  /// Wallet membership (users in / out / role change) changed.
  walletMembership,

  /// Wallet list (created / deleted / joined) changed.
  wallets,

  /// The authenticated session changed (login or logout). Dart-side
  /// providers MUST invalidate their cached state on this kind:
  /// the local SQLite was wiped, so anything cached from the prior
  /// user is now stale and must not bleed across the user switch.
  /// `wallet_id` is always `None` for this kind.
  session,
  ;
}
