// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_cancel`, `wait_or_cancel`, `ws_loop`

/// Start the realtime WS worker. Picks up token + wallet + ws_url
/// from the client state at call time. Idempotent — if a worker is
/// already running, returns `Ok(())` and does nothing.
Future<void> connectRealtime() =>
    RustLib.instance.api.crateIntegrationWsConnectRealtime();

/// Stop the realtime WS worker. Idempotent.
Future<void> disconnectRealtime() =>
    RustLib.instance.api.crateIntegrationWsDisconnectRealtime();
