-- Add UNIQUE constraint to idempotency_key for deduplication
--
-- Semantics:
-- - event_id (UUID, UNIQUE): Server-generated, for event identity and references
-- - idempotency_key (VARCHAR, UNIQUE): Client-generated per UI action, for deduplication
--
-- Both are UNIQUE and generated at insert time:
-- - event_id: Always generated by server via DEFAULT gen_random_uuid()
-- - idempotency_key: Must be provided by client per UI action, prevents duplicate form submissions

-- First, populate any NULL idempotency_key values to allow the constraint
UPDATE events SET idempotency_key = 'legacy_' || event_id::text WHERE idempotency_key IS NULL;

-- Make idempotency_key NOT NULL and add UNIQUE constraint
ALTER TABLE events ALTER COLUMN idempotency_key SET NOT NULL;
ALTER TABLE events ADD CONSTRAINT events_idempotency_key_unique UNIQUE (idempotency_key);
