// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class ClientError with _$ClientError implements FrbException {
  const ClientError._();

  /// Network error (connectivity, timeout, DNS, etc.)
  const factory ClientError.network(
    String field0,
  ) = ClientError_Network;

  /// Authentication failed: credentials rejected, token expired, or invalid JWT
  const factory ClientError.authDeclined() = ClientError_AuthDeclined;

  /// Authentication chain broken: refresh token expired/revoked, must re-login
  const factory ClientError.authExpired() = ClientError_AuthExpired;

  /// HTTP response body is invalid JSON or missing required fields
  const factory ClientError.invalidResponse(
    String field0,
  ) = ClientError_InvalidResponse;

  /// Storage/database operation failed (SQLite error, file I/O, etc.)
  const factory ClientError.storage(
    String field0,
  ) = ClientError_Storage;

  /// Sync operation failed (event application, hash mismatch, etc.)
  const factory ClientError.sync_(
    String field0,
  ) = ClientError_Sync;

  /// Invalid input to a public API
  const factory ClientError.invalidInput(
    String field0,
  ) = ClientError_InvalidInput;

  /// Authorization failed: insufficient permissions for the requested operation
  const factory ClientError.insufficientPermission(
    String field0,
  ) = ClientError_InsufficientPermission;

  /// Internal error (should never happen in production)
  const factory ClientError.internal(
    String field0,
  ) = ClientError_Internal;
}
