// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Event stored in local database.
class StoredEvent {
  final String id;
  final String walletId;
  final String aggregateType;
  final String aggregateId;
  final String eventType;
  final String eventData;
  final String timestamp;
  final int version;
  final bool synced;

  const StoredEvent({
    required this.id,
    required this.walletId,
    required this.aggregateType,
    required this.aggregateId,
    required this.eventType,
    required this.eventData,
    required this.timestamp,
    required this.version,
    required this.synced,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      walletId.hashCode ^
      aggregateType.hashCode ^
      aggregateId.hashCode ^
      eventType.hashCode ^
      eventData.hashCode ^
      timestamp.hashCode ^
      version.hashCode ^
      synced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          walletId == other.walletId &&
          aggregateType == other.aggregateType &&
          aggregateId == other.aggregateId &&
          eventType == other.eventType &&
          eventData == other.eventData &&
          timestamp == other.timestamp &&
          version == other.version &&
          synced == other.synced;
}
