// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/error.dart';
import '../types/models.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_tables`
// These functions are ignored because they have generic arguments: `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageState`

/// True if init() has been called successfully (process-wide).
Future<bool> isReady() => RustLib.instance.api.crateDatabaseRepositoryIsReady();

Future<void> init({required String path}) =>
    RustLib.instance.api.crateDatabaseRepositoryInit(path: path);

Future<String?> configGet({required String key}) =>
    RustLib.instance.api.crateDatabaseRepositoryConfigGet(key: key);

Future<void> configSet({required String key, required String value}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryConfigSet(key: key, value: value);

Future<void> configRemove({required String key}) =>
    RustLib.instance.api.crateDatabaseRepositoryConfigRemove(key: key);

Future<void> clearAll() =>
    RustLib.instance.api.crateDatabaseRepositoryClearAll();

Future<void> clearWallet({required String walletId}) =>
    RustLib.instance.api.crateDatabaseRepositoryClearWallet(walletId: walletId);

Future<void> eventsInsert({required StoredEvent e}) =>
    RustLib.instance.api.crateDatabaseRepositoryEventsInsert(e: e);

Future<void> eventsUpdateEventData(
        {required String eventId, required String eventDataJson}) =>
    RustLib.instance.api.crateDatabaseRepositoryEventsUpdateEventData(
        eventId: eventId, eventDataJson: eventDataJson);

Future<List<StoredEvent>> eventsGetAll({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryEventsGetAll(walletId: walletId);

Future<List<StoredEvent>> eventsGetUnsynced({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryEventsGetUnsynced(walletId: walletId);

Future<void> eventsMarkSynced({required List<String> ids}) =>
    RustLib.instance.api.crateDatabaseRepositoryEventsMarkSynced(ids: ids);

Future<BigInt> eventsDeleteUnsynced({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryEventsDeleteUnsynced(walletId: walletId);

Future<void> eventsDeleteAllForWallet({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryEventsDeleteAllForWallet(walletId: walletId);

Future<PlatformInt64> eventsCount({required String walletId}) =>
    RustLib.instance.api.crateDatabaseRepositoryEventsCount(walletId: walletId);

Future<List<StoredEvent>> eventsGetForAggregate(
        {required String walletId,
        required String aggregateType,
        required String aggregateId}) =>
    RustLib.instance.api.crateDatabaseRepositoryEventsGetForAggregate(
        walletId: walletId,
        aggregateType: aggregateType,
        aggregateId: aggregateId);

Future<List<Contact>> loadContactsFromTables({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryLoadContactsFromTables(walletId: walletId);

Future<List<Transaction>> loadTransactionsFromTables(
        {required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseRepositoryLoadTransactionsFromTables(walletId: walletId);
