// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/models.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_db`

Future<bool> isReady() => RustLib.instance.api.crateDatabaseStorageIsReady();

Future<void> init({required String path}) =>
    RustLib.instance.api.crateDatabaseStorageInit(path: path);

Future<String?> configGet({required String key}) =>
    RustLib.instance.api.crateDatabaseStorageConfigGet(key: key);

Future<void> configSet({required String key, required String value}) =>
    RustLib.instance.api.crateDatabaseStorageConfigSet(key: key, value: value);

Future<void> configRemove({required String key}) =>
    RustLib.instance.api.crateDatabaseStorageConfigRemove(key: key);

Future<void> clearAll() => RustLib.instance.api.crateDatabaseStorageClearAll();

Future<void> clearWallet({required String walletId}) =>
    RustLib.instance.api.crateDatabaseStorageClearWallet(walletId: walletId);

Future<void> eventsInsert({required StoredEvent e}) =>
    RustLib.instance.api.crateDatabaseStorageEventsInsert(e: e);

Future<void> eventsUpdateEventData(
        {required String eventId, required String eventDataJson}) =>
    RustLib.instance.api.crateDatabaseStorageEventsUpdateEventData(
        eventId: eventId, eventDataJson: eventDataJson);

Future<List<StoredEvent>> eventsGetAll({required String walletId}) =>
    RustLib.instance.api.crateDatabaseStorageEventsGetAll(walletId: walletId);

Future<List<StoredEvent>> eventsGetUnsynced({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseStorageEventsGetUnsynced(walletId: walletId);

Future<void> eventsMarkSynced({required List<String> ids}) =>
    RustLib.instance.api.crateDatabaseStorageEventsMarkSynced(ids: ids);

Future<BigInt> eventsDeleteUnsynced({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseStorageEventsDeleteUnsynced(walletId: walletId);

Future<void> eventsDeleteAllForWallet({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseStorageEventsDeleteAllForWallet(walletId: walletId);

Future<PlatformInt64> eventsCount({required String walletId}) =>
    RustLib.instance.api.crateDatabaseStorageEventsCount(walletId: walletId);

Future<List<StoredEvent>> eventsGetForAggregate(
        {required String walletId,
        required String aggregateType,
        required String aggregateId}) =>
    RustLib.instance.api.crateDatabaseStorageEventsGetForAggregate(
        walletId: walletId,
        aggregateType: aggregateType,
        aggregateId: aggregateId);

Future<List<Contact>> loadContactsFromTables({required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseStorageLoadContactsFromTables(walletId: walletId);

Future<List<Transaction>> loadTransactionsFromTables(
        {required String walletId}) =>
    RustLib.instance.api
        .crateDatabaseStorageLoadTransactionsFromTables(walletId: walletId);
